# Generated by Django 5.2.8 on 2026-09-28 08:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Node code')),
                ('name', models.CharField(max_length=64, verbose_name='Node name')),
                ('node_type', models.CharField(choices=[('parking', 'Parking'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('charging', 'Charging'), ('intersection', 'Intersection')], default='intersection', max_length=20, verbose_name='Node type')),
                ('x', models.FloatField(verbose_name='X coordinate')),
                ('y', models.FloatField(verbose_name='Y coordinate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Map node',
                'verbose_name_plural': 'Map nodes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='AGV code')),
                ('name', models.CharField(max_length=64, verbose_name='AGV name')),
                ('model_name', models.CharField(blank=True, max_length=64, verbose_name='Model')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('charging', 'Charging'), ('offline', 'Offline'), ('error', 'Error')], default='idle', max_length=16, verbose_name='Status')),
                ('battery_percent', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Battery (%)')),
                ('payload_capacity', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Payload capacity (kg)')),
                ('speed', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Speed (m/s)')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='Last heartbeat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agvs', to='SchedulingDecision.mapnode', verbose_name='Current node')),
            ],
            options={
                'verbose_name': 'AGV',
                'verbose_name_plural': 'AGVs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=32, unique=True, verbose_name='Task number')),
                ('cargo_name', models.CharField(max_length=64, verbose_name='Cargo name')),
                ('cargo_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Cargo weight (kg)')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2, verbose_name='Priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('route', models.JSONField(blank=True, default=dict, verbose_name='Planned route')),
                ('total_distance', models.FloatField(default=0, verbose_name='Total distance (m)')),
                ('estimated_duration', models.FloatField(default=0, verbose_name='Estimated duration (s)')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled start')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled end')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_agv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='SchedulingDecision.agv', verbose_name='Assigned AGV')),
                ('dropoff_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_tasks', to='SchedulingDecision.mapnode', verbose_name='Dropoff node')),
                ('pickup_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_tasks', to='SchedulingDecision.mapnode', verbose_name='Pickup node')),
            ],
            options={
                'verbose_name': 'Transport task',
                'verbose_name_plural': 'Transport tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], max_length=16, verbose_name='Algorithm')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('route', models.JSONField(blank=True, default=dict, verbose_name='Route')),
                ('distance', models.FloatField(default=0, verbose_name='Distance (m)')),
                ('estimated_duration', models.FloatField(default=0, verbose_name='Duration (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dispatched at')),
                ('agv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_records', to='SchedulingDecision.agv', verbose_name='AGV')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='SchedulingDecision.transporttask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Dispatch record',
                'verbose_name_plural': 'Dispatch records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Distance (m)')),
                ('speed_limit', models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Speed limit (m/s)')),
                ('bidirectional', models.BooleanField(default=True, verbose_name='Bidirectional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='SchedulingDecision.mapnode', verbose_name='End node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='SchedulingDecision.mapnode', verbose_name='Start node')),
            ],
            options={
                'verbose_name': 'Map edge',
                'verbose_name_plural': 'Map edges',
                'ordering': ['start_node__code', 'end_node__code'],
                'constraints': [models.UniqueConstraint(fields=('start_node', 'end_node'), name='uniq_edge_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='transporttask',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='SchedulingD_status_32de06_idx'),
        ),
        migrations.AddIndex(
            model_name='transporttask',
            index=models.Index(fields=['assigned_agv', 'status'], name='SchedulingD_assigne_eb0b7b_idx'),
        ),
    ]
