# Generated by Django 5.2.8 on 2026-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingDecision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('busy', '执行任务'), ('charging', '充电点'), ('offline', '离线'), ('error', '故障')], default='idle', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='algorithm',
            field=models.CharField(choices=[('single', '单台调度'), ('batch', '多台调度')], max_length=16, verbose_name='Algorithm'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='node_type',
            field=models.CharField(choices=[('parking', '停车点'), ('pickup', '取货点'), ('dropoff', '放货点'), ('charging', '充电点'), ('intersection', '路径节点')], default='intersection', max_length=20, verbose_name='Node type'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '普通'), (3, '高'), (4, '紧急')], default=2, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='status',
            field=models.CharField(choices=[('pending', '待调度'), ('assigned', '已分配'), ('in_progress', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
