# Generated by Django 5.2.8 on 2026-09-28 11:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingDecision', '0002_alter_agv_status_alter_dispatchrecord_algorithm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='调度批次')),
                ('algorithm', models.CharField(choices=[('single_sequence', '单台多任务顺序优化'), ('multi_vns', '多台变邻域优化')], max_length=32, verbose_name='优化算法')),
                ('objective_name', models.CharField(max_length=128, verbose_name='目标函数')),
                ('task_count', models.PositiveIntegerField(default=0, verbose_name='任务数')),
                ('agv_count', models.PositiveIntegerField(default=0, verbose_name='使用 AGV 数')),
                ('makespan_seconds', models.FloatField(default=0, verbose_name='完工时间(秒)')),
                ('total_distance', models.FloatField(default=0, verbose_name='总里程(米)')),
                ('total_wait_seconds', models.FloatField(default=0, verbose_name='总等待时间(秒)')),
                ('iteration_count', models.PositiveIntegerField(default=0, verbose_name='搜索迭代次数')),
                ('baseline_makespan_seconds', models.FloatField(default=0, verbose_name='基线完工时间(秒)')),
                ('improvement_percent', models.FloatField(default=0, verbose_name='改进率(%)')),
                ('assignments', models.JSONField(blank=True, default=dict, verbose_name='AGV 分配与顺序')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='优化指标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '调度优化记录',
                'verbose_name_plural': '调度优化记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='agv',
            options={'ordering': ['code'], 'verbose_name': 'AGV', 'verbose_name_plural': 'AGV'},
        ),
        migrations.AlterModelOptions(
            name='dispatchrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '调度记录', 'verbose_name_plural': '调度记录'},
        ),
        migrations.AlterModelOptions(
            name='mapedge',
            options={'ordering': ['start_node__code', 'end_node__code'], 'verbose_name': '地图道路', 'verbose_name_plural': '地图道路'},
        ),
        migrations.AlterModelOptions(
            name='mapnode',
            options={'ordering': ['code'], 'verbose_name': '地图节点', 'verbose_name_plural': '地图节点'},
        ),
        migrations.AlterModelOptions(
            name='transporttask',
            options={'ordering': ['-created_at'], 'verbose_name': '运输任务', 'verbose_name_plural': '运输任务'},
        ),
        migrations.AddField(
            model_name='transporttask',
            name='optimization_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='优化详情'),
        ),
        migrations.AddField(
            model_name='transporttask',
            name='planned_wait_seconds',
            field=models.FloatField(default=0, verbose_name='计划避碰等待(秒)'),
        ),
        migrations.AddField(
            model_name='transporttask',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, verbose_name='执行顺序'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='battery_percent',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='电量(%)'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='AGV 编号'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='current_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agvs', to='SchedulingDecision.mapnode', verbose_name='当前位置'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True, verbose_name='最后心跳'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='model_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='payload_capacity',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='额定载重(kg)'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='speed',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='速度(米/秒)'),
        ),
        migrations.AlterField(
            model_name='agv',
            name='status',
            field=models.CharField(choices=[('idle', '空闲'), ('busy', '执行任务'), ('charging', '充电中'), ('offline', '离线'), ('error', '故障')], default='idle', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='algorithm',
            field=models.CharField(choices=[('single', '单台调度'), ('batch', '多台调度')], max_length=16, verbose_name='调度算法'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='调度时间'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='distance',
            field=models.FloatField(default=0, verbose_name='调度里程(米)'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='estimated_duration',
            field=models.FloatField(default=0, verbose_name='预计耗时(秒)'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='调度说明'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='route',
            field=models.JSONField(blank=True, default=dict, verbose_name='调度路线'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='success',
            field=models.BooleanField(default=True, verbose_name='成功'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='SchedulingDecision.transporttask', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='bidirectional',
            field=models.BooleanField(default=True, verbose_name='双向通行'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='距离(米)'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='SchedulingDecision.mapnode', verbose_name='终点'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='speed_limit',
            field=models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='限速(米/秒)'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='SchedulingDecision.mapnode', verbose_name='起点'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='节点编码'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='name',
            field=models.CharField(max_length=64, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='node_type',
            field=models.CharField(choices=[('parking', '停车点'), ('pickup', '取货点'), ('dropoff', '放货点'), ('charging', '充电点'), ('intersection', '路径节点')], default='intersection', max_length=20, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='x',
            field=models.FloatField(verbose_name='X 坐标'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='y',
            field=models.FloatField(verbose_name='Y 坐标'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='assigned_agv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='SchedulingDecision.agv', verbose_name='执行 AGV'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='cargo_name',
            field=models.CharField(max_length=64, verbose_name='货物名称'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='cargo_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='货物重量(kg)'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际完成'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='dropoff_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_tasks', to='SchedulingDecision.mapnode', verbose_name='放货点'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='estimated_duration',
            field=models.FloatField(default=0, verbose_name='单任务耗时(秒)'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='pickup_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_tasks', to='SchedulingDecision.mapnode', verbose_name='取货点'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '普通'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='route',
            field=models.JSONField(blank=True, default=dict, verbose_name='规划路线'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划完成'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划开始'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际开始'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='status',
            field=models.CharField(choices=[('pending', '待调度'), ('assigned', '已分配'), ('in_progress', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='task_no',
            field=models.CharField(max_length=32, unique=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='total_distance',
            field=models.FloatField(default=0, verbose_name='总里程(米)'),
        ),
        migrations.AlterField(
            model_name='transporttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='transporttask',
            name='schedule_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='SchedulingDecision.schedulerun', verbose_name='调度优化记录'),
        ),
        migrations.AddIndex(
            model_name='transporttask',
            index=models.Index(fields=['schedule_run', 'sequence_number'], name='SchedulingD_schedul_389d24_idx'),
        ),
    ]
