# Generated by Django 5.2.8 on 2026-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingDecision', '0003_schedulerun_alter_agv_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='障碍物编码')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='障碍物名称')),
                ('x', models.FloatField(verbose_name='X 坐标')),
                ('y', models.FloatField(verbose_name='Y 坐标')),
                ('width', models.FloatField(default=1, verbose_name='宽度')),
                ('height', models.FloatField(default=1, verbose_name='高度')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '地图障碍物',
                'verbose_name_plural': '地图障碍物',
                'ordering': ['code'],
            },
        ),
    ]
